//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

//modified by Linh
public class ClassSchedule
{
    #region data fields
    private List<Course> schedule;
    #endregion

    #region Properties
    public List<Course> Schedule
    {
        get
        {
            return schedule;
        }
    }
    #endregion

    #region methods
    public ClassSchedule()  //constructor
	{
       // List<Course> schedule = new List<Course>();
	}

	public virtual void AddClass(string cC, string cL)
	{
        schedule.Add(new Course(cC, cL));
	}

	public virtual void RemoveClass(Course course)
	{
		//Havent figured out how to remove a class object from List
	}
    #endregion
}

