//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Course
{
    #region data fields
    private string courseCode;
    private string courseLevel;
    #endregion

    #region Properties

    private string CourseCode
    {
        get
        {
            return this.courseCode;
        }
        set
        {
            this.courseCode = value;
        }
    }

    private string CourseLevel
    {
        get
        {
            return this.courseLevel;
        }
        set
        {
            this.courseLevel = value;
        }
    }
    #endregion

    #region methods

    public Course() //default constructor
	{
        this.courseCode = "";
        this.courseLevel = "";
	}

	public Course(string cC, string cL) //constructor with 2 args
	{
        this.courseCode = cC;
        this.courseLevel = cL;
	}

	public void UpdateCourseCode(string cC)
	{
        this.courseCode = cC;
	}

	public void UpdateCourseLevel(string cL)
	{
        this.courseLevel = cL;
	}
    #endregion

}