//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Course
{
    #region data fields
    private string courseCode;
    private string courseLevel;
    #endregion

    #region Properties
    public string CourseCode
    {
        get
        {
            return courseCode;
        }
        set
        {
            courseCode = value;
        }
    }

    public string CourseLevel
    {
        get
        {
            return courseLevel;
        }
        set
        {
            courseLevel = value;
        }
    }
    #endregion

    #region methods
    public Course() //default constructor
	{
        courseCode = "";
        courseLevel = "";
	}

	public Course(string cC, string cL) //constructor with 2 args
	{
        courseCode = cC;
        courseLevel = cL;
	}

	public void UpdateCourseCode(string cC)
	{
        courseCode = cC;
	}

	public void UpdateCourseLevel(string cL)
	{
        courseLevel = cL;
	}
    #endregion

}

