//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Course
{
	public virtual string courseCode
	{
		get;
		set;
	}

	public virtual string courseLevel
	{
		get;
		set;
	}

	public virtual void Class()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Class(string cC, string cL)
	{
		throw new System.NotImplementedException();
	}

	public virtual void UpdateCourseCode(string cC)
	{
		throw new System.NotImplementedException();
	}

	public virtual void UpdateCourseLevel(string cL)
	{
		throw new System.NotImplementedException();
	}

}

