//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

//modified by Linh
public class ListingList
{
    //data - a listing_list is a List structure of Listing types
    private List<Listing> listing_list;

    //Property
	public List<Listing> Listing_List  
	{
		get
        {
            return listing_list;
        }
	}

	/*public virtual Search Search
	{
		get;
		set;
	}*/

    //method - Add a new listing to the listing_list
    public ListingList()    //constructor
    {
        List<Listing> listing_list = new List<Listing>();
    }

	public void Add(Listing a_listing)
	{
        listing_list.Add(a_listing);
	}

}

