//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Eric ToDo
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Text;

public class ListingList
{

    public DataBase db = new DataBase();
    public List<int> listinglist = new List<int>();

    public List<Listing> listingList
	{

		get { return this.listingList; }
        set { this.listingList = value; }

	}

    public string connString
    {

        get { return this.connString; }
        set { this.connString = db.ConnString; }

    }

    public int SearchForListing(Listing listing)
    {

        int listingId = listing.Listing_id;

        using (SqlConnection conn = new SqlConnection())
        {

            conn.ConnectionString = db.ConnString;
            conn.Open();

            string query = "SELECT  listing_id FROM ListingList WHERE any like " + listing.Listing_id;

            using (SqlCommand command = new SqlCommand(query, conn))
            {

                using (SqlDataReader reader = command.ExecuteReader())
                {

                    while (reader.Read())
                    {

                        

                    }

                }

            }

        }

        return listingId;

    }

    public void CreateList()
    {

        using (SqlConnection conn = new SqlConnection(db.ConnString))
        {

            conn.Open();

            string query = "SELECT listing_id FROM ListingList";

            using (SqlCommand command = new SqlCommand(query, conn))
            {

                using (SqlDataReader dbreader = command.ExecuteReader())
                {

                    while (dbreader.Read())
                    {

                        listinglist.Add(Convert.ToInt32(dbreader.GetString(0)));

                    }

                }

            }

        }

    }

}

