//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Eric TODO

using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Text;

public class Marketplace
{

    public const int LISTINGLIFE = 30;

    private int listingLifetime;
    private List<Listing> listings;
    private DataBase db = new DataBase();

	public int ListingLifeTime
	{

		get { return this.listingLifetime; }
		set { this.listingLifetime = value; }

    }

	public List<Listing> Listing
	{

		get { return this.listings; }

    }

	public virtual void RenewListing(Listing listing)
	{

        using (SqlConnection conn = new SqlConnection(db.ConnString))
        {

            conn.Open();

            string sql;

            if (listing.Listing_id == -1)
            {

                sql = "UPDATE [UserList] "
                        + "SET listinglife = 30"
                        + "WHERE listing_id = @lid";

            }

            else
            {

                sql = "UPDATE [UserList] "
                        + "SET listinglife = 30"
                        + "WHERE listing_id = @lid";

            }

            SqlCommand command = new SqlCommand(sql, conn);

            command.Parameters.AddWithValue("lid", listing.Listing_id);

            command.ExecuteNonQuery();

        }

	}

	public virtual void AddListing(Listing listing,int trader_id)
	{

        listing.CreateListing(trader_id);

	}

	public virtual void RemoveListing(Listing listing)
	{
		throw new System.NotImplementedException();
	}

	public virtual void FilterResults()
	{
		throw new System.NotImplementedException();
	}

	public virtual ListingList SearchAll()
	{
		throw new System.NotImplementedException();
	}

	public virtual ListingList SearchByAuthor(string author)
	{
		throw new System.NotImplementedException();
	}

	public virtual ListingList SearchByCourse(string cC, string cL)
	{
		throw new System.NotImplementedException();
	}

	public virtual ListingList SearchByISBN(string isbn)
	{
		throw new System.NotImplementedException();
	}

	public virtual ListingList SearchFromSchedule(ClassSchedule classSchedule)
	{
		throw new System.NotImplementedException();
	}

}

