//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Eric TODO

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Marketplace
{

    public const int LISTINGLIFE = 30;

    private int listingLifetime;
    private List<Listing> listing;

	public int ListingLifeTime
	{

		get { return this.listingLifetime; }
		set { this.listingLifetime = value; }

    }

	public List<Listing> Listing
	{

		get { return this.listing; }

    }

	public virtual void RenewListing(Listing listing)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddListing(ListingList listingList)
	{
		throw new System.NotImplementedException();
	}

	public virtual void RemoveListing(Listing listing)
	{
		throw new System.NotImplementedException();
	}

	public virtual void FilterResults()
	{
		throw new System.NotImplementedException();
	}

	public virtual ListingList SearchAll()
	{
		throw new System.NotImplementedException();
	}

	public virtual ListingList SearchByAuthor(string author)
	{
		throw new System.NotImplementedException();
	}

	public virtual ListingList SearchByCourse(string cC, string cL)
	{
		throw new System.NotImplementedException();
	}

	public virtual ListingList SearchByISBN(string isbn)
	{
		throw new System.NotImplementedException();
	}

	public virtual ListingList SearchFromSchedule(ClassSchedule classSchedule)
	{
		throw new System.NotImplementedException();
	}

}

