//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Eric TODO

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Moderator : Account
{

    // creates an account object
	public Account account
	{
		get { return this.account; }
		set { this.account = new Account(); }
	}

	public virtual List<Listing> listing
	{
		get { return this.listing; }
		set { this.listing = new List<Listing>(); }
	}

	public virtual Marketplace marketplace
	{
		get { return this.marketplace; }
		set {; }
	}

	public virtual void RemoveListing(Listing listing)
	{
		throw new System.NotImplementedException();
	}

	public virtual void WarnTrader(Trader trader)
	{
		throw new System.NotImplementedException();
	}

	public virtual void BanTrader(Trader trader)
	{
		throw new System.NotImplementedException();
	}

	public virtual int SearchForUser(Trader trader)
	{
		throw new System.NotImplementedException();
	}

	public virtual void ViewUserInfo(Trader trader)
	{
		throw new System.NotImplementedException();
	}

	public virtual void ViewSystemStats()
	{
		throw new System.NotImplementedException();
	}

}

