//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Eric TODO

using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Text;

public class Moderator : Account
{

    DataBase db = new DataBase();

    // creates an account object
	public Account account
	{

		get { return this.account; }
		set { this.account = value; }

    }

	public List<Listing> listing
	{

		get { return this.listing; }
		set { this.listing = value; }

    }

	public Marketplace marketplace
	{

		get { return this.marketplace; }

	}

	public void RemoveListing(Listing listing)
	{

        db.Delete("Listings", "listing_id", listing.Listing_id);

	}

	public void WarnTrader(Trader trader)
	{

        using (SqlConnection conn = new SqlConnection())
        {

            conn.ConnectionString = db.ConnString;

            string query = "UPDATE TraderList Set warnings = warnings + 1 WHERE trader_id = " + trader.Trader_id;

            SqlCommand command = new SqlCommand(query, conn);

            command.ExecuteNonQuery();

        }
	
    }

	public void BanTrader(Trader trader)
	{

		db.Delete("TraderList","trader_id",trader.Trader_id);

    }

	public Trader SearchForUser(int traderid)
	{

        Trader temptrader = new Trader();

        db.SearchForListing("TraderList")

	}

	public Trader ViewUserInfo(Trader trader)
	{

        throw new System.NotImplementedException();

	}

	public virtual void ViewSystemStats()
	{
		throw new System.NotImplementedException();
	}

}

