//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Eric TODO

using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Text;

public class TraderList : DataBase
{

    private DataBase db = new DataBase();
    private List<int> traderlist = new List<int>();

    public List<int> Traderlist
    {
        get
        {
            return this.traderlist;
        }
        set
        {
            this.traderlist = value;
        }
    }

	public virtual void Add(Trader trader) // this function probably needs to be moved to the trader class
	{

        using (SqlConnection conn = new SqlConnection(db.ConnString))
        {
            //conn.ConnectionString = db.ConnString;
            conn.Open();

            string sql;

            if (trader.Trader_id == -1)
            {
                sql = "INSERT into [TraderList] (username, password, deleted, classschedule,warnings,firstname,lastname,email) "
                        + "VALUES (@uname , @pword, 0,null,0,@fname,@lname,@mail)";
                        //+ " SET trader_id = cast(SCOPE_IDENTITY() as int)";
            }

            else
            {
                sql = "INSERT into [TraderList] (trader_id, username, password, deleted, classschedule) "
                        + "VALUES ( @id, @uname , @pword, 0, null )"
                        + " SET IDENTITY_INSERT TraderList ON ";
            }



            using (SqlCommand command = new SqlCommand(sql, conn))
            {
                command.Parameters.AddWithValue("id", trader.Trader_id);
                command.Parameters.AddWithValue("uname", trader.Username);
                command.Parameters.AddWithValue("pword", trader.Password);
                command.Parameters.AddWithValue("fname", trader.FirstName);
                command.Parameters.AddWithValue("lname", trader.LastName);
                command.Parameters.AddWithValue("mail", trader._Email.ToString());


            if (trader.Trader_id == -1)
            {

                 trader.Trader_id = Convert.ToInt32(command.ExecuteScalar());

            }

            else
            {

                command.Parameters.AddWithValue("trader_id", trader.Trader_id);

                command.ExecuteNonQuery();

            } 
          }
        }

	}


    public void CreateList()
    {

        using (SqlConnection conn = new SqlConnection(db.ConnString))
        {

            conn.Open();

            string query = "SELECT trader_id FROM TraderList";

            using (SqlCommand command = new SqlCommand(query, conn))
            {

                using (SqlDataReader dbreader = command.ExecuteReader())
                {

                    while (dbreader.Read())
                    {

                        traderlist.Add(Convert.ToInt32(dbreader.GetString(0)));

                    }

                }

            }

        }

    }

	public List<Trader> SearchForUser(int traderid)
	{

        List<Trader> traders = new List<Trader>();

        traders = db.SearchForTrader(traderid);

        return traders;

    }

    //Overloaded SearchForUser method using a string representing a username
    public List<Trader> SearchForUser(string uName)
    {
        List<Trader> traders = new List<Trader>();

        traders = db.SearchForTrader(uName);

        return traders;
    }

    public bool UserExists(string uName)
    {
        List<Trader> traders = new List<Trader>();

        traders = db.SearchForTrader(uName);

        if (traders.Count > 0)
            return true;
        else
            return false;
    }

}

