//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Eric TODO

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class UserList
{
	public virtual void Add(Trader trader)
	{
		throw new System.NotImplementedException();
	}

	public virtual userList SearchForUser()
	{
		throw new System.NotImplementedException();
	}

}

