//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Account
{
	public virtual string username
	{
		get
        {
            return username;
        }
		set
        {
            username = value;
        }
	}

	public virtual string password
	{
		get
        {
            return password;
        }
		set
        {
            password = value;
        }
	}

	public virtual Email email
	{
		get;
		set;
	}

	public virtual string firstName
	{
		get
        {
            return firstName;
        }
		set
        {
            firstName = value;
        }
	}

	public virtual string lastName
	{
		get
        {
            return lastName;
        }
		set
        {
            lastName = value;
        }
	}

	public virtual Email Email
	{
		get;
		set;
	}

	public Account()
	{
	}

	public Account(string uName, string pword, string fName, string lName, string email)
	{
        username = uName;
        password = pword;
        firstName = fName;
        lastName = lName;
        this.Email.email = email;
	}

	public virtual string ChangePassword(string pass)
	{
	}

}

