//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ClassSchedule
{
	public virtual List<Course> schedule
	{
        get
        {
            return schedule;
        }
	}

	/*public virtual Course <<Struct>> Class
	{
		get;
		set;
	}*/

	public ClassSchedule()
    {
        schedule.Add(new Course());
    }

	public virtual void AddClass(string cC, string cL)
	{
        if(schedule[0].courseCode  == "" && schedule[0].courseLevel == "")
        {
            schedule[0].UpdateCourseCode(cC);
            schedule[0].UpdateCourseLevel(cL);
        }
        else
            schedule.Add(new Course(cC, cL));
	}

	public virtual void RemoveClass(Course course)
	{
        schedule.Remove(course);
	}

}

