//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ClassSchedule
{
	public virtual List<Course> schedule
	{
        get
        {
            return schedule;
        }
	}

	public ClassSchedule()
    {
    }

	public virtual void AddClass(string cC, string cL)
	{
        if (!schedule.Contains(new Course(cC, cL)))
            schedule.Add(new Course(cC, cL));
	}

	public virtual void RemoveClass(Course course)
	{
        if(schedule.Count != 0)
            schedule.Remove(course);
	}

}