//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Course
{
	public virtual string courseCode
	{
		get
        {
            return courseCode;
        }
        set
        {
            courseCode = value;
        }
	}

	public virtual string courseLevel
	{
		get
        {
            return courseLevel;
        }
		set
        {
            courseLevel = value;
        }
	}

	public Course()
	{
        this.courseCode = "";
        this.courseLevel = "";
	}

	public Course(string cC, string cL)
	{
        this.courseCode = cC;
        this.courseLevel = cL;
	}

	public virtual void UpdateCourseCode(string cC)
	{
        this.courseCode = cC;
	}

	public virtual void UpdateCourseLevel(string cL)
	{
        this.courseLevel = cL;
	}

}

