//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DataBase
{
	public virtual string connString
	{
		get;
		set;
	}

	public virtual Marketplace Marketplace
	{
		get;
		set;
	}

	public virtual WatchList WatchList
	{
		get;
		set;
	}

	public virtual SellList SellList
	{
		get;
		set;
	}

	public virtual UserList UserList
	{
		get;
		set;
	}

	public virtual ListingList ListingList
	{
		get;
		set;
	}

	public virtual void Insert()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Remove()
	{
		throw new System.NotImplementedException();
	}

}

