//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Email
{
	public virtual string email
	{
		get;
		set;
	}

	public virtual void OpenMail()
	{
		throw new System.NotImplementedException();
	}

	public virtual void SendMail(Email email)
	{
		throw new System.NotImplementedException();
	}

}

