//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ClassSchedule
{
	public virtual List<Course> schedule
	{
		get;
		set;
	}

	public virtual Course <<Struct>> Class
	{
		get;
		set;
	}

	public ClassSchedule()
	{
	}

	public virtual void AddClass(string cC, string cL)
	{
		throw new System.NotImplementedException();
	}

	public virtual void RemoveClass(Course course)
	{
		throw new System.NotImplementedException();
	}

}

