//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class WatchList
{
	public virtual IEnumerable<Listing> Listing
	{
		get;
		set;
	}

	public virtual void AddToWatchList(Listing listing)
	{
		throw new System.NotImplementedException();
	}

	public virtual void RemoveFromWatchList(Listing listing)
	{
		throw new System.NotImplementedException();
	}

}

